name: Build
on: [push, pull_request]
jobs:
  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: build
        run: scripts/windowsBuild.ps1
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: build
        run: bash scripts/linuxBuild.bash
  build-Fedora:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: build
        run: bash scripts/linuxBuild.bash
